# Generated by Django 5.1.7 on 2025-03-28 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('History', '病史'), ('Lab', '化验报告'), ('Prescription', '处方'), ('Note', '医疗笔记')], max_length=50)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(blank=True)),
                ('attachments', models.FileField(upload_to='ehr_attachments/')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
