# Generated by Django 5.1.7 on 2025-03-28 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='record_type',
            field=models.CharField(choices=[('History', 'Medical History'), ('Lab', 'Laboratory Report'), ('Prescription', 'Prescription'), ('Note', 'Medical Notes')], max_length=50),
        ),
    ]
