# Generated by Django 5.1.7 on 2025-04-30 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0003_alter_medicalrecord_record_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecordTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='medicalrecord',
            options={'ordering': ['-creation_date']},
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='is_confidential',
            field=models.BooleanField(default=False, help_text='Mark as confidential to restrict access'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Archived', 'Archived'), ('Pending', 'Pending Review')], default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='record_type',
            field=models.CharField(choices=[('History', 'Medical History'), ('Lab', 'Laboratory Report'), ('Prescription', 'Prescription'), ('Note', 'Medical Notes'), ('Imaging', 'Imaging Results'), ('Surgery', 'Surgical Report'), ('Consultation', 'Consultation Notes'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='tags',
            field=models.ManyToManyField(blank=True, to='ehr.medicalrecordtag'),
        ),
    ]
