# Generated by Django 5.1.7 on 2025-04-30 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0004_medicalrecordtag_alter_medicalrecord_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecordAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_text', models.TextField()),
                ('diagnosis', models.JSONField(blank=True, null=True)),
                ('medications', models.JSONField(blank=True, null=True)),
                ('treatments', models.JSONField(blank=True, null=True)),
                ('abnormal_values', models.JSONField(blank=True, null=True)),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('medical_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='ehr.medicalrecord')),
            ],
        ),
    ]
